### ISSUE TITLE
[BUG] SODStockMarket, Trade history index out of range

### ISSUE THREAD

**Issue by joveice** [Ven0maus/SOD.Common#32]
**Describe the bug**
Pressing back (forward?, left button) on the "Trade history" when you have multiple pages causes index out of range error.
Might happen the other way, but this seems to be consistent.

![image](https://github.com/Ven0maus/SOD.Common/assets/14098624/6f53a498-e617-4730-bb7c-c7b130f3fc75)

**Reproduction scenario**

1. Trade enough to have multiple pages (two seems enough)
2. Click the left button

**Expected behavior**
Rollover like the other pages or nothing / remove button.

**Additional context**

Game: v37.08

Mods used:
- Venomaus-SODCommon-2.0.0
- BepInEx-BepInExPack_IL2CPP-6.0.667
- Piepieonline-Asset_Bundle_Loader-1.0.4
- Venomaus-SODStockMarket-2.0.5
- Venomaus-SODQoL-1.1.4
- TeamSpyraxi-PrintBugfix-0.1.1
- TeamSpyraxi-HoursOfOperation-0.1.0
- Piepieonline-DDSLoader-1.0.4
- Piepieonline-RealEstateCruncherApp-1.0.7
- PixelJunkies-Cruncher_Correction-1.0.1
- PixelJunkies-No_Notice_Nonsense-0.1.5

```
[Error  :Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SOD.StockMarket.Implementation.Trade.TradeHistoryPagination.SetHistories(TradeHistory[] slots)
   at SOD.StockMarket.Implementation.Trade.TradeHistoryPagination.Previous()
   at SOD.StockMarket.Implementation.Cruncher.Content.AppTradeHistory.Previous()
   at (il2cpp delegate trampoline) System.Void_System.Action(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] During invoking native->managed trampoline
Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SOD.StockMarket.Implementation.Trade.TradeHistoryPagination.SetHistories(TradeHistory[] slots)
   at SOD.StockMarket.Implementation.Cruncher.Content.AppTradeHistory.UpdateHistories(Object sender, TimeChangedArgs e)
   at SOD.Common.Helpers.Time.OnTimeChanged(TimeData previous, TimeData current)
   at SOD.Common.Patches.SessionDataPatches.SessionData_Update.Postfix()
   at DMD<SessionData::Update>(SessionData this)
   at (il2cpp -> managed) Update(IntPtr , Il2CppMethodInfo* )
[Error  :Il2CppInterop] During invoking native->managed trampoline
Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at SOD.StockMarket.Implementation.Trade.TradeHistoryPagination.SetHistories(TradeHistory[] slots)
   at SOD.StockMarket.Implementation.Cruncher.Content.AppTradeHistory.UpdateHistories(Object sender, TimeChangedArgs e)
   at SOD.Common.Helpers.Time.OnTimeChanged(TimeData previous, TimeData current)
   at SOD.Common.Patches.SessionDataPatches.SessionData_Update.Postfix()
   at DMD<SessionData::Update>(SessionData this)
   at (il2cpp -> managed) Update(IntPtr , Il2CppMethodInfo* )
```

**Comment by Ven0maus** [comment]
Fixed in v2.0.6 thanks for the bugreport!
